name: MindSpore Gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 0,2,4,6...,22th hour every day (every 2 hours)
    - cron:  '0 */2 * * *'

jobs:
  build:

